name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: "release hpi"
    steps:
      - name: Build
        uses: offa/maven-action@f7410831c994990b4402c017391edf6da7d2e944
        with:
          java-version: 17
          pmd: false
      - name: Release
        uses: softprops/action-gh-release@86463358d88d57dec8e9c65bc1d9c9d2fe9ce180
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*.hpi
