name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: "release hpi"
    steps:
      - name: Build
        uses: offa/maven-action@5416431fe9db78ba30619456a16ee72bd961deb1
        with:
          java-version: 17
          pmd: false
      - name: Release
        uses: softprops/action-gh-release@f82d31e53e61a962573dd0c5fcd6b446ca78871f
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*.hpi
